config/routes.rb
Rails.application.routes.draw do
  get 'trending/rank'

  devise_for :users
  resources :articles do
    resources :reviews
  end
  root 'articles#index'


  get 'a1', to: 'articles#a1'
  get 'a2', to: 'articles#a2'
  get 'a3', to: 'articles#a3'
  get 'a4', to: 'articles#a4'
  get 'a5', to: 'articles#a5'




end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :reviews
  
has_attached_file :article_img, styles: { :article_index => "250x250>", :article_show => "325x475>" }, :default_url => "/images/:style/missing.png"
validates_attachment_content_type :article_img, :content_type => /\Aimage\/.*\z/




end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :articles
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
  class ArticlesController < ApplicationController
   before_action :find_article, only: [:show, :edit, :update, :destroy, :a1, :a2, :a3, :a4, :a5]


  def index
    if params[:category].blank?
    @articles = Article.all.order("created_at DESC")

  else
    @category_id = Category.find_by(name: params[:category]).id
    @articles = Article.where(:category_id => @category_id).order("created_at DESC")

  end
  end

  def new
    @article = Article.new
  end

  def show
   @article  = Article.find_by(id:params[:id])
   @article1 = Article.find_by(id:params[:id])
   @article2 = Article.find_by(id:params[:id])
   @article3 = Article.find_by(id:params[:id])
   @article4 = Article.find_by(id:params[:id])
   @article5 = Article.find_by(id:params[:id])
  end

  def a1
    json1 = File.read('app/assets/javascripts/article1.json')
    @article1 = JSON.parse(json1)
  end

  def a2
    json2 = File.read('app/assets/javascripts/article2.json')
    @article2 = JSON.parse(json2)
  end

  def a3
    json3 = File.read('app/assets/javascripts/article3.json')
    @article3 = JSON.parse(json3)
  end

  def a4
    json4 = File.read('app/assets/javascripts/article4.json')
    @article4 = JSON.parse(json4)
  end

  def a5
    json5 = File.read('app/assets/javascripts/article5.json')
    @article5 = JSON.parse(json5)
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to root_path
    else
      render 'new'
  end
end

def edit

end


  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to root_path
    else
      render 'new'
  end
end



def edit
end

def update
  if @article.update(article_params)
    redirect_to article_path(@article)
  else
    render 'edit'
  end
end

def destroy
  @article.destroy
  redirect_to root_path
end

  private
      def article_params
        params.require(:article).permit(:title, :description, :writer)
      end

      def find_article
        @article = Article.find_by(id:params[:id])
      end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_article

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.article_id = @articles.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to article_path(@article1)
    else
      render 'new'
    end
  end

  private

      def review_params
            params.require(:review).permit(:rating, :comment)
      end

      def find_article
        @article = Article.find(params[:article_id])
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/articles/_form.html.erb
<%=  simple_form_for @article do |f| %>
 <%= f.input :title, label: "Article Title" %>
 <%= f.input :description %>
 <%= f.input :writer %>
 <%= f.button :submit %>

<% end %>

app/views/articles/a1.html.erb
<h2><%= @article1["title"] %></h2>

<p><%= @article1["body"][0]["model"]["text"] %></p>
<p><%= @article1["body"][1]["model"]["text"] %></p>


<img src="https://picsum.photos/640/420/?random" alt="Vestibulum pellentesque laoreet urna, eget dignissim lorem maximus vel" height="420" width="640">

<p><%= @article1["body"][3]["model"]["text"] %></p>
<p><%= @article1["body"][4]["model"]["text"] %></p>
<l1><%= @article1["body"][5]["model"]["items"] %></li>

app/views/articles/a2.html.erb
<title><%= @article2["title"] %></title>

<h1><%= @article2["body"][0]["model"]["text"] %></h1>
<img src="https://picsum.photos/640/420/?random" alt="Vestibulum pellentesque laoreet urna, eget dignissim lorem maximus vel" height="420" width="640">
<p><%= @article2["body"][2]["model"]["text"] %></p>
<p><%= @article2["body"][3]["model"]["text"] %></p>
<img src="https://picsum.photos/640/420/?random" alt="Curabitur dictum leo bibendum lacus ultrices fringilla et quis justo" height="420" width="640">
<p><%= @article2["body"][4]["model"]["text"] %></p>
<p><%= @article2["body"][5]["model"]["text"] %></p>
<img src="https://picsum.photos/640/420/?random" alt="Curabitur dictum leo bibendum lacus ultrices fringilla et quis justo" height="420" width="640">
<p><%= @article2["body"][7]["model"]["text"] %></p>

app/views/articles/a3.html.erb
<h1><%= @article3["title"] %></h1>

<h2><%= @article3["body"][0]["model"]["text"] %></h2>
<p><%= @article3["body"][1]["model"]["text"] %></p>
<p><%= @article3["body"][2]["model"]["text"] %></p>
<p><%= @article3["body"][3]["model"]["text"] %></p>
<p><%= @article3["body"][4]["model"]["text"] %></p>
<p><%= @article3["body"][5]["model"]["text"] %></p>

app/views/articles/a4.html.erb
<h1><%= @article4["title"] %></h1>

<h2><%= @article4["body"][0]["model"]["text"] %></h2>
<p><%= @article4["body"][1]["model"]["text"] %></p>
<l1><%= @article4["body"][2]["model"]["list"] %></l1>
<p><%= @article4["body"][3]["model"]["text"] %></p>
<l1><%= @article4["body"][4]["model"]["list"] %></l1>
<p><%= @article4["body"][5]["model"]["text"] %></p>

app/views/articles/a5.html.erb
<h1><%= @article5["title"] %></h1>

<h2><%= @article5["body"][0]["model"]["text"] %></h2>
<img src="https://picsum.photos/640/420/?random" alt="Donec purus augue, lobortis et velit maximus, rutrum scelerisque ipsum" height="420" width="640">
<img src="https://picsum.photos/640/420/?random" alt="Etiam at nisl diam" height="420" width="640">
<p><%= @article5["body"][3]["model"]["text"] %></p>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<h2><%= link_to article.title, article_path(article) %></h2>
<% end %>


<h1><%= link_to "JSON 1", a1_path %></h1>
<h1><%= link_to "JSON 2", a2_path %></h1>
<h1><%= link_to "JSON 3", a3_path %></h1>
<h1><%= link_to "JSON 4", a4_path %></h1>
<h1><%= link_to "JSON 5", a5_path %></h1>

app/views/articles/new.html.erb
<h1> New article </h1>


<%= render 'form' %>

app/views/articles/show.html.erb
<div class="col-md-8"
  <h2><%= @article.title %></h2>
  <h3><%= @article.writer %></h3>
  <p><%= @article.description %></p>
</div>

<div class="row">
  <div class="col-md-4">


    <div>
      <%= link_to "Add Review", new_article_review_path(@article) %>
    </div>




<%= link_to "Back", root_path %>

<% if user_signed_in? %>

<% if @article.user_id == current_user.id %>

  <%= link_to "Edit", edit_article_path(@article) %>
  <%= link_tp "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>

<% end %>




<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">

    <div class="container">
      <div class="navbar-header">
        <%= link_to "Yours", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% if user_signed_in? %>
             <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
             <% else %>
             <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-expanded="false">Trending by <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
              <li>
                <%= link_to category.name, articles_path(category: category.name), class: "link" %>
                </li>
                <% end %>
                </ul>
                <li>



          <% if user_signed_in? %>
          <li><%= link_to "Add article", new_article_path %></l1>
            <% end %>
            </ul>
      </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


 <div class="container"
<%= yield %>
</div>

</body>
</html>

app/views/reviews/_form.html.erb
  <%= simple_form_for([@article, @article.reviews.build]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>

<%= simple_form_for([@article1, @article1.reviews.build]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/_form1.html.erb
  <%= simple_form_for([@article1, @article1.reviews.build]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>

app/views/reviews/new.html.erb
<h6> New Review </h6>

<%= render 'form' %>